docker:
   swarms:
       - id: swarm
         name: Swarm
         apiVersion: v1.30
         description: Swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock