docker:
   swarms:
       - id: dev
         name: Development
         apiVersion: v1.30
         description: Dev swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock
       - id: prod
         name: Production
         apiVersion: v1.30
         description: Prod swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock