docker:
   swarms:
       - id: swarm
         name: Swarm
         apiVersion: v1.37
         description: Swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock
       - id: swarmProd
         name: Swarm Prod
         apiVersion: v1.37
         description: Swarm Prod
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock