docker:
   swarms:
       - id: 1
         name: dev
         apiVersion: v1.30
         description: dev swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock
       - id: 2
         name: prod
         apiVersion: v1.30
         description: prod swarm
         client:
            protocol: unix
            unixSocketPath: /var/run/docker.sock